[alarm] アラーム機能の追加
bisnii/hacku pull request #22
Opened 2021-03-04 09:21 UTC by sachi-github

**概要**
現段階では、時間・アラーム音・bgmを決めて確定を押し、スタートボタンを押すことでタイマーがスタートする。
bgmは途中で変えられる。
止める際はストップボタンを押す。また、確定ボタンを押しても止まる。

2021-03-04 11:30 UTC, yochimonji requested changes
すまんが多少修正願いたいm(-_-)m

2021-03-04 11:30 UTC, yochimonji commented on templates/index.html
> +                <option value="60m">60</option>
このあたりのvalueの設定すっかり忘れてた笑
ありがとー

2021-03-04 11:30 UTC, yochimonji commented on static/scripts/alarm.js
> +    }
このままだと音楽の数を増やしたいときに大変なことになるから変えましょう。とりあえず下みたいな感じでいかが？下の方法じゃなくて音楽数を増やしても大丈夫な方法であればなんでも大丈夫よー。
- 保存してある音楽のフォルダ名をbgm-rain.mp3などに変更
- if文の中で
```
let bgm = new Audio('../bgm/bgm-' + $bgmChoice + '.mp3');
bgm.loop = true;
bgm.play()
```

2021-03-04 11:30 UTC, yochimonji commented on static/scripts/alarm.js
> +        }
bgmと同様にお願いします

2021-03-04 11:30 UTC, yochimonji commented on static/scripts/alarm.js
> +function time() {
これは少し細かくて申し訳ないんだけど、timeとcountDownでループになってるから、時間がずれやすいのと処理が多少重た目なのが気になる…下のような改善はいかがでしょうか？試行錯誤の結果こうなったならこのままでもいいよー
- bgmはSTARTボタンが押されたらはじめに実行
- alarmだけ`setTimeout(time, timelimit)`によって、timelimit時間経過後に1回だけ実行

2021-03-05 01:24 UTC, yochimonji commented
確定押したあとに2回START押したらSTOPが反応しなくなってしまった…

2021-03-05 03:25 UTC, sachi-github commented
STOPが反応しない？
タイムは止まってない？bgmは今確認した感じ止まってないから直します。

2021-03-05 05:21 UTC, yochimonji approved these changes
+1
色々改善ありがと-

2021-03-05 05:21 UTC, merged

2021-03-05 05:30 UTC, sachi-github commented
こちらこそ不具合だらけで申し訳ない